.TH "Kunnymann.Base.NavigationModuleBase" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.NavigationModuleBase \- \fBNavigation\fP DI 객체  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKunnymann\&.Base\&.ModuleBase\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBKunnymann\&.Base\&.ModuleBase\fP
.in +1c
.ti -1c
.RI "\fBModuleBase\fP ()"
.br
.RI "생성자 Default FMS를 구축합니다 "
.ti -1c
.RI "void \fBRunOnMainThread\fP (params Action[] action)"
.br
.RI "Main thread에 액션을 밀어넣습니다 "
.ti -1c
.RI "virtual void \fBModuleInitialize\fP ()"
.br
.RI "모듈의 초기화 사이클 "
.ti -1c
.RI "virtual void \fBModuleUpdate\fP ()"
.br
.RI "모듈의 Unity update 사이클 "
.ti -1c
.RI "virtual void \fBModuleTerminate\fP ()"
.br
.RI "모듈의 종료 사이클 "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Dispose\&. "
.in -1c

Package Functions inherited from \fBKunnymann\&.Base\&.ModuleBase\fP
.in +1c
.ti -1c
.RI "void \fBProcess\fP (\fBTransitionCommand\fP transition=\fBTransitionCommand\&.None\fP)"
.br
.RI "모듈 동작을 처리합니다 "
.in -1c

Properties inherited from \fBKunnymann\&.Base\&.ModuleBase\fP
.in +1c
.ti -1c
.RI "\fBModuleState\fP \fBCurrentState\fP\fR [get]\fP"
.br
.RI "모듈 상태 "
.in -1c
.SH "Detailed Description"
.PP 
\fBNavigation\fP DI 객체 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
