.TH "Kunnymann.Base.ModuleManager" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.ModuleManager \- Module manager\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModuleBase\fP \fBGetModule\fP (string moduleName)"
.br
.RI "모듈 객체를 반환합니다 "
.ti -1c
.RI "T \fBGetModule< T >\fP ()"
.br
.RI "모듈 객체를 반환합니다\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBModuleBase\fP > \fBModules\fP = new List<\fBModuleBase\fP>()"
.br
.RI "모듈 컨테이너 "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBModuleManager\fP \fBInstance\fP\fR [get]\fP"
.br
.RI "Singleton 객체 "
.in -1c
.SH "Detailed Description"
.PP 
Module manager\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBModuleBase\fP Kunnymann\&.Base\&.ModuleManager\&.GetModule (string moduleName)"

.PP
모듈 객체를 반환합니다 
.PP
\fBParameters\fP
.RS 4
\fImoduleName\fP 모듈 이름
.RE
.PP
\fBReturns\fP
.RS 4
모듈 객체
.RE
.PP

.SS "T \fBKunnymann\&.Base\&.ModuleManager\&.GetModule\fP< T > ()"

.PP
모듈 객체를 반환합니다\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 모듈 클래스
.RE
.PP
\fBReturns\fP
.RS 4
모듈 객체
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIModuleBase\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
