.TH "Kunnymann.Base.ScriptExcutionOrder" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.ScriptExcutionOrder \- 스크립트 실행 순위 조절 Attribute  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScriptExcutionOrder\fP (int order)"
.br
.RI "생성자 "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBOrder\fP"
.br
.RI "실행 순서 "
.in -1c
.SH "Detailed Description"
.PP 
스크립트 실행 순위 조절 Attribute 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Kunnymann\&.Base\&.ScriptExcutionOrder\&.ScriptExcutionOrder (int order)"

.PP
생성자 
.PP
\fBParameters\fP
.RS 4
\fIorder\fP 순위
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
