.TH "Kunnymann.Base.Debugger.ErrorListener" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.Debugger.ErrorListener \- 에러 리스너  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCheck\fP (Exception error, string description='', bool needthrowerror=false, bool report=true)"
.br
.RI "에러를 체크합니다 "
.in -1c
.SH "Detailed Description"
.PP 
에러 리스너 
.SH "Member Function Documentation"
.PP 
.SS "static void Kunnymann\&.Base\&.Debugger\&.ErrorListener\&.Check (Exception error, string description = \fR''\fP, bool needthrowerror = \fRfalse\fP, bool report = \fRtrue\fP)\fR [static]\fP"

.PP
에러를 체크합니다 
.PP
\fBParameters\fP
.RS 4
\fIerror\fP Exception
.br
\fIdescription\fP 설명
.br
\fIneedthrowerror\fP Throw 여부
.br
\fIstackSize\fP stack 사이즈, 기본 값은 2레벨 까지
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
