.TH "Kunnymann.UI.Popup.PopupContainer" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.UI.Popup.PopupContainer \- UIPopup Prefab들을 관리하는 Container\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKunnymann\&.Base\&.Utility\&.MonoBehaviourSingleton< T >\fP\&.
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBPopupUnit\fP \fBGetUIPopup\fP (string popupName)"
.br
.RI "UIPopup을 리스트로부터 찾아와, Instantiate하여 반환합니다\&. "
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBKunnymann\&.Base\&.Utility\&.MonoBehaviourSingleton< T >\fP
.in +1c
.ti -1c
.RI "static T \fBInstance\fP\fR [get]\fP"
.br
.RI "싱글턴 객체 "
.in -1c
.SH "Detailed Description"
.PP 
UIPopup Prefab들을 관리하는 Container\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBPopupUnit\fP Kunnymann\&.UI\&.Popup\&.PopupContainer\&.GetUIPopup (string popupName)\fR [package]\fP"

.PP
UIPopup을 리스트로부터 찾아와, Instantiate하여 반환합니다\&. 
.PP
\fBParameters\fP
.RS 4
\fIpopupName\fP UIPopup 프리팹 이름
.RE
.PP
\fBReturns\fP
.RS 4
UIPopup
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
