.TH "Kunnymann.Base.Utility.MonoBehaviourSingleton< T >" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.Utility.MonoBehaviourSingleton< T > \- MonoBehaviour 싱글톤 추상 클래스  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBKunnymann\&.UI\&.Popup\&.PopupContainer\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "static T \fBInstance\fP\fR [get]\fP"
.br
.RI "싱글턴 객체 "
.in -1c
.SH "Detailed Description"
.PP 
MonoBehaviour 싱글톤 추상 클래스 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP MonoBehaviour 클래스
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIMonoBehaviour\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
