.TH "Kunnymann.Base.Debugger" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.Debugger
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugger\fP"
.br
.RI "\fBKunnymann\fP 패키지의 디버거 클래스 "
.ti -1c
.RI "class \fBDebuggerConfig\fP"
.br
.RI "\fBDebugger\fP config\&. "
.ti -1c
.RI "class \fBErrorListener\fP"
.br
.RI "에러 리스너 "
.ti -1c
.RI "class \fBLogConst\fP"
.br
.RI "디버거 로그 상수 "
.ti -1c
.RI "class \fBLogHelper\fP"
.br
.RI "Log helper 클래스 "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLogLevel\fP { \fBAll\fP = 0, \fBDebug\fP, \fBInfo\fP, \fBWarning\fP, \fBError\fP, \fBFatal\fP }"
.br
.RI "Log level\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBKunnymann\&.Base\&.Debugger\&.LogLevel\fP"

.PP
Log level\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIAll \fP
All level\&. 
.TP
\f(BIDebug \fP
Debug level\&. 
.TP
\f(BIInfo \fP
Info level\&. 
.TP
\f(BIWarning \fP
Warning level\&. 
.TP
\f(BIError \fP
Error level\&. 
.TP
\f(BIFatal \fP
Fatal level\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
