.TH "Kunnymann.UI.Popup.PopupUtility" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.UI.Popup.PopupUtility \- \fBPopup\fP 확장 메소드 클래스  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static T \fBSetText< T >\fP (this T uiPopup, params string[] texts)"
.br
.RI "UIPopup을 구성하고 있는 TextFields에 텍스트를 설정합니다\&. "
.ti -1c
.RI "static T \fBSetLocalizedText< T >\fP (this T uiPopup, bool forceEmpty=true)"
.br
.RI "Popup에 지정된 TextFields에 LocalizedText를 설정합니다\&. "
.ti -1c
.RI "static T \fBSetButtonEvent< T >\fP (this T uiPopup, params UnityAction[] actions)"
.br
.RI "UIPopup을 구성하고 있는 Button에 이벤트를 등록합니다\&. "
.ti -1c
.RI "static T \fBSetDependencyOnView< T >\fP (this T uiPop, \fBViewUnit\fP view)"
.br
.RI "UIPopup의 Dependency를 설정합니다\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBPopup\fP 확장 메소드 클래스 
.SH "Member Function Documentation"
.PP 
.SS "static T Kunnymann\&.UI\&.Popup\&.PopupUtility\&.SetButtonEvent< T > (this T uiPopup, params UnityAction[] actions)\fR [static]\fP"

.PP
UIPopup을 구성하고 있는 Button에 이벤트를 등록합니다\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP UIPopup 클래스
.RE
.PP
\fBParameters\fP
.RS 4
\fIuiPopup\fP UIPopup
.br
\fIactions\fP Button에 할당될 이벤트
.RE
.PP
\fBReturns\fP
.RS 4
UIPopup
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIPopupUnit\fP
.SS "static T Kunnymann\&.UI\&.Popup\&.PopupUtility\&.SetDependencyOnView< T > (this T uiPop, \fBViewUnit\fP view)\fR [static]\fP"

.PP
UIPopup의 Dependency를 설정합니다\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP UIPopup 클래스
.RE
.PP
\fBParameters\fP
.RS 4
\fIuiPop\fP UIPopup
.br
\fIview\fP View
.RE
.PP
\fBReturns\fP
.RS 4
UIPopup
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIPopupUnit\fP
.SS "static T Kunnymann\&.UI\&.Popup\&.PopupUtility\&.SetLocalizedText< T > (this T uiPopup, bool forceEmpty = \fRtrue\fP)\fR [static]\fP"

.PP
Popup에 지정된 TextFields에 LocalizedText를 설정합니다\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP UIPopup 클래스
.RE
.PP
\fBParameters\fP
.RS 4
\fIuiPopup\fP UIPopup
.RE
.PP
\fBReturns\fP
.RS 4
UIPopup
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIPopupUnit\fP
.SS "static T Kunnymann\&.UI\&.Popup\&.PopupUtility\&.SetText< T > (this T uiPopup, params string[] texts)\fR [static]\fP"

.PP
UIPopup을 구성하고 있는 TextFields에 텍스트를 설정합니다\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP UIPopup 클래스
.RE
.PP
\fBParameters\fP
.RS 4
\fIuiPopup\fP UIPopup
.br
\fItexts\fP TextField에 들어갈 값
.RE
.PP
\fBReturns\fP
.RS 4
UIPopup
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIPopupUnit\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
