.TH "Kunnymann.Base.Debugger.DebuggerConfig" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.Debugger.DebuggerConfig \- \fBDebugger\fP config\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKunnymann\&.Utility\&.SingletonScripatableObject< T >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLogLevel\fP \fBLogLevel\fP = \fBLogLevel\&.All\fP"
.br
.RI "Log level\&. "
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBKunnymann\&.Utility\&.SingletonScripatableObject< T >\fP
.in +1c
.ti -1c
.RI "static T \fBInstance\fP\fR [get]\fP"
.br
.RI "싱글턴 객체 "
.in -1c
.SH "Detailed Description"
.PP 
\fBDebugger\fP config\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
