.TH "Kunnymann.UI" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.UI
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDraggableHandle\fP"
.br
.RI "드래그 가능한 핸들 클래스 "
.ti -1c
.RI "class \fBUIFadeInOut\fP"
.br
.RI "\fBUI\fP Fade In & Out 애니메이션을 적용하는 UITransition\&. "
.ti -1c
.RI "class \fBUIFriendlyPopIn\fP"
.br
.RI "\fBUI\fP Friendly \fBPopup\fP 애니메이션을 적용하는 UITransition\&. "
.ti -1c
.RI "class \fBUIPopIn\fP"
.br
.RI "\fBUI\fP \fBPopup\fP 애니메이션을 적용하는 UITransition\&. "
.ti -1c
.RI "class \fBUISlide\fP"
.br
.RI "\fBUI\fP Slide 애니메이션을 적용하는 UITransition\&. "
.ti -1c
.RI "class \fBUITransitionBase\fP"
.br
.RI "\fBUI\fP Animation Transition을 적용하는 \fBBase\fP Class\&. "
.ti -1c
.RI "class \fBViewUnit\fP"
.br
.RI "UI를 구성하는 View의 최소 단위 "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSlideDirections\fP { \fBLEFT\fP, \fBRIGHT\fP, \fBUP\fP, \fBDOWN\fP }"
.br
.RI "Slide 방향 "
.ti -1c
.RI "enum \fBVisibleState\fP { \fBAppearing\fP, \fBAppeared\fP, \fBDisappearing\fP, \fBDisappeared\fP }"
.br
.RI "UI visible state\&. "
.ti -1c
.RI "enum \fBDraggableHandleState\fP { \fBNone\fP = 0, \fBHidden\fP, \fBVisible\fP }"
.br
.RI "Draggable ui state\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBKunnymann\&.UI\&.SlideDirections\fP"

.PP
Slide 방향 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILEFT \fP
Left to right\&. 
.TP
\f(BIRIGHT \fP
Right to left\&. 
.TP
\f(BIUP \fP
Up to bottom\&. 
.TP
\f(BIDOWN \fP
Bottom to up\&. 
.SS "enum \fBKunnymann\&.UI\&.VisibleState\fP"

.PP
\fBUI\fP visible state\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIAppearing \fP
Appearing\&. 
.TP
\f(BIAppeared \fP
Appeared\&. 
.TP
\f(BIDisappearing \fP
Disappearing\&. 
.TP
\f(BIDisappeared \fP
Disappeared\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
