.TH "Kunnymann.Base.Utility" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.Utility
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBManagerInitUtility\fP"
.br
.RI "\fBModuleManager\fP 초기화 유틸리티 "
.ti -1c
.RI "class \fBMonoBehaviourSingleton< T >\fP"
.br
.RI "MonoBehaviour 싱글톤 추상 클래스 "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
