.TH "Kunnymann.Base.Utility.ManagerInitUtility" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.Utility.ManagerInitUtility \- \fBModuleManager\fP 초기화 유틸리티  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitModules\fP (\fBModuleManager\fP \fBModuleManager\fP)"
.br
.RI "ModuleManager를 초기화하여, 직렬화된 모듈 객체들을 수집합니다 "
.in -1c
.SH "Detailed Description"
.PP 
\fBModuleManager\fP 초기화 유틸리티 
.SH "Member Function Documentation"
.PP 
.SS "static void Kunnymann\&.Base\&.Utility\&.ManagerInitUtility\&.InitModules (\fBModuleManager\fP ModuleManager)\fR [static]\fP"

.PP
ModuleManager를 초기화하여, 직렬화된 모듈 객체들을 수집합니다 
.PP
\fBParameters\fP
.RS 4
\fI\fBModuleManager\fP\fP \fBModuleManager\fP 객체
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
