.TH "Kunnymann.Utility.SingletonScripatableObject< T >" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Utility.SingletonScripatableObject< T > \- Scriptable object 싱글톤 추상 클래스  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBKunnymann\&.Base\&.Debugger\&.DebuggerConfig\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "static T \fBInstance\fP\fR [get]\fP"
.br
.RI "싱글턴 객체 "
.in -1c
.SH "Detailed Description"
.PP 
Scriptable object 싱글톤 추상 클래스 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Scriptable object 클래스
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fISingletonScripatableObject<T>\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
