.TH "Kunnymann.Navigation.AStarPathGenerator" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Navigation.AStarPathGenerator \- A* \fBPath\fP Generator\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPath\fP \fBFindPath\fP (Vector3 position, \fBINode\fP endNode, \fBTransitionType\fP transition)"
.br
.RI "Find path\&. "
.in -1c
.SS "Static Package Functions"

.in +1c
.ti -1c
.RI "static \fBPath\fP \fBFindPath\fP (\fBINode\fP startNode, \fBINode\fP endNode, \fBTransitionType\fP transitionType)"
.br
.RI "Find path\&. "
.in -1c
.SH "Detailed Description"
.PP 
A* \fBPath\fP Generator\&. 
.SH "Member Function Documentation"
.PP 
.SS "static \fBPath\fP Kunnymann\&.Navigation\&.AStarPathGenerator\&.FindPath (\fBINode\fP startNode, \fBINode\fP endNode, \fBTransitionType\fP transitionType)\fR [static]\fP, \fR [package]\fP"

.PP
Find path\&. 
.PP
\fBParameters\fP
.RS 4
\fIstartNode\fP Start node
.br
\fIendNode\fP End node
.br
\fItransitionType\fP Transition type
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "static \fBPath\fP Kunnymann\&.Navigation\&.AStarPathGenerator\&.FindPath (Vector3 position, \fBINode\fP endNode, \fBTransitionType\fP transition)\fR [static]\fP"

.PP
Find path\&. 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP Vector3 position
.br
\fIendNode\fP End node
.br
\fItransition\fP Transition type
.RE
.PP
\fBReturns\fP
.RS 4
\fBPath\fP
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
