.TH "Kunnymann.Base" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseBehaviour\fP"
.br
.RI "모듈 기본 Behaviour "
.ti -1c
.RI "class \fBBaseObject\fP"
.br
.RI "모듈 기본 오브젝트 "
.ti -1c
.RI "class \fBBaseScriptableObject\fP"
.br
.RI "모듈 기본 ScriptableObject "
.ti -1c
.RI "interface \fBCommonBase\fP"
.br
.RI "모듈 공통 인터페이스 "
.ti -1c
.RI "class \fBConstValue\fP"
.br
.RI "상수값 "
.ti -1c
.RI "class \fBModuleBase\fP"
.br
.RI "모듈의 공통 베이스 "
.ti -1c
.RI "class \fBModuleManager\fP"
.br
.RI "Module manager\&. "
.ti -1c
.RI "class \fBNavigationModuleBase\fP"
.br
.RI "\fBNavigation\fP DI 객체 "
.ti -1c
.RI "class \fBPOIFeatureData\fP"
.br
.RI "AR POI 데이터 "
.ti -1c
.RI "class \fBPOIModuleBase\fP"
.br
.RI "POI DI 객체 "
.ti -1c
.RI "class \fBScriptExcutionOrder\fP"
.br
.RI "스크립트 실행 순위 조절 Attribute "
.ti -1c
.RI "class \fBVLModuleBase\fP"
.br
.RI "VPS Module의 DI 객체 "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBModuleState\fP { \fBCreated\fP, \fBInactive\fP, \fBActive\fP, \fBTerminated\fP }"
.br
.RI "모듈의 상태 "
.ti -1c
.RI "enum \fBTransitionCommand\fP { \fBInitialize\fP, \fBNone\fP, \fBTerminate\fP }"
.br
.RI "모듈의 상태 전이를 위한 명령어 "
.ti -1c
.RI "enum \fBVLState\fP { \fBNone\fP, \fBInitial\fP, \fBReceived\fP, \fBFail\fP, \fBSuccess\fP, \fBOutofService\fP }"
.br
.RI "VPS engine state\&. "
.ti -1c
.RI "enum \fBTrackerType\fP { \fBDefault\fP = 0, \fBSourceProprietaryTech\fP, \fBLocalTech\fP, \fBSimulator\fP }"
.br
.RI "VPS engine type\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBEventHandler\fP ()"
.br
.RI "모듈 이벤트 핸들러 "
.ti -1c
.RI "delegate void \fBEventHandler< TEventArg >\fP (TEventArg eventArg)"
.br
.RI "모듈 이벤트 핸들러 "
.ti -1c
.RI "delegate void \fBEventHandler< TEventArg1, TEventArg2 >\fP (TEventArg1 eventArg1, TEventArg2 eventArg2)"
.br
.RI "모듈 이벤트 핸들러 "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBKunnymann\&.Base\&.ModuleState\fP"

.PP
모듈의 상태 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BICreated \fP
생성 
.TP
\f(BIInactive \fP
비활성화 
.TP
\f(BIActive \fP
활성화 
.TP
\f(BITerminated \fP
제거 
.SS "enum \fBKunnymann\&.Base\&.TrackerType\fP"

.PP
VPS engine type\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIDefault \fP
기본값 
.TP
\f(BISourceProprietaryTech \fP
원천 기술사 VPS engine 
.TP
\f(BILocalTech \fP
자사 VPS engine 
.TP
\f(BISimulator \fP
시뮬레이터 
.SS "enum \fBKunnymann\&.Base\&.TransitionCommand\fP"

.PP
모듈의 상태 전이를 위한 명령어 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIInitialize \fP
초기화 명령 
.TP
\f(BINone \fP
명령 없음 
.TP
\f(BITerminate \fP
제거 명령 
.SS "enum \fBKunnymann\&.Base\&.VLState\fP"

.PP
VPS engine state\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
초기화 대기 
.TP
\f(BIInitial \fP
초기화 완료 
.TP
\f(BIReceived \fP
VPS로부터 응답이 수신된 상태 
.TP
\f(BIFail \fP
인식 실패 
.TP
\f(BISuccess \fP
인식 성공 
.TP
\f(BIOutofService \fP
서비스 미지원 
.SH "Function Documentation"
.PP 
.SS "delegate void \fBKunnymann\&.Base\&.EventHandler\fP< TEventArg > (TEventArg eventArg)"

.PP
모듈 이벤트 핸들러 
.PP
\fBTemplate Parameters\fP
.RS 4
\fITEventArg\fP 타입
.RE
.PP
\fBParameters\fP
.RS 4
\fIeventArg\fP 파라미터
.RE
.PP

.SS "delegate void \fBKunnymann\&.Base\&.EventHandler\fP< TEventArg1, TEventArg2 > (TEventArg1 eventArg1, TEventArg2 eventArg2)"

.PP
모듈 이벤트 핸들러 
.PP
\fBTemplate Parameters\fP
.RS 4
\fITEventArg1\fP 타입 1
.br
\fITEventArg2\fP 타입 2
.RE
.PP
\fBParameters\fP
.RS 4
\fIeventArg1\fP 파라미터 1
.br
\fIeventArg2\fP 파라미터 2
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
