.TH "Kunnymann.Navigation.PathUnit" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Navigation.PathUnit \- Units that make up the navigation path\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKunnymann\&.Navigation\&.ILink\fP, and \fBKunnymann\&.Navigation\&.INode\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBID\fP\fR [get]\fP"
.br
.RI "ID\&. "
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.RI "Name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Units that make up the navigation path\&. 
.SH "Property Documentation"
.PP 
.SS "string Kunnymann\&.Navigation\&.PathUnit\&.ID\fR [get]\fP"

.PP
ID\&. 
.PP
Implemented in \fBKunnymann\&.Navigation\&.CurrentPoint\fP\&.
.SS "string Kunnymann\&.Navigation\&.PathUnit\&.Name\fR [get]\fP"

.PP
Name\&. 
.PP
Implemented in \fBKunnymann\&.Navigation\&.CurrentPoint\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
