.TH "Kunnymann.Base.POIFeatureData" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.POIFeatureData \- AR POI 데이터  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPOIFeatureData\fP (string id, string dpName, string type, Vector3 position, string source, string description)"
.br
.RI "생성자 "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBID\fP\fR [get]\fP"
.br
.RI "ID\&. "
.ti -1c
.RI "string \fBDPName\fP\fR [get]\fP"
.br
.RI "Display name\&. "
.ti -1c
.RI "string \fBType\fP\fR [get]\fP"
.br
.RI "Type\&. "
.ti -1c
.RI "Vector3 \fBPosition\fP\fR [get]\fP"
.br
.RI "Unity position\&. "
.ti -1c
.RI "string \fBSource\fP\fR [get]\fP"
.br
.RI "데이터 소스 "
.ti -1c
.RI "string \fBDescription\fP\fR [get]\fP"
.br
.RI "POI description\&. "
.in -1c
.SH "Detailed Description"
.PP 
AR POI 데이터 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Kunnymann\&.Base\&.POIFeatureData\&.POIFeatureData (string id, string dpName, string type, Vector3 position, string source, string description)"

.PP
생성자 
.PP
\fBParameters\fP
.RS 4
\fIid\fP ID
.br
\fIdpName\fP Display name
.br
\fItype\fP Type
.br
\fIposition\fP Position
.br
\fIsource\fP Data
.br
\fIdescription\fP Description
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
