.TH "Kunnymann.Base.Debugger.LogHelper" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.Debugger.LogHelper \- Log helper 클래스  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLog\fP (\fBLogLevel\fP lv, object msg)"
.br
.RI "레벨에 따른 로그를 출력합니다 "
.in -1c
.SH "Detailed Description"
.PP 
Log helper 클래스 
.SH "Member Function Documentation"
.PP 
.SS "void Kunnymann\&.Base\&.Debugger\&.LogHelper\&.Log (\fBLogLevel\fP lv, object msg)"

.PP
레벨에 따른 로그를 출력합니다 
.PP
\fBParameters\fP
.RS 4
\fIlv\fP 로그 레벨
.br
\fImsg\fP 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIException\fP 유효하지 않는 레벨에 대한 에러
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
