.TH "Kunnymann.Navigation.NavigationConfig" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Navigation.NavigationConfig \- \fBNavigation\fP configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.RI "Initialize navigation raw data\&. "
.ti -1c
.RI "List< \fBINode\fP > \fBGetNodeContainer\fP ()"
.br
.RI "Return \fBINode\fP container\&. "
.ti -1c
.RI "List< \fBILink\fP > \fBGetLinkContainer\fP ()"
.br
.RI "Return \fBILink\fP container\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBNavigation\fP configuration\&. 
.SH "Member Function Documentation"
.PP 
.SS "List< \fBILink\fP > Kunnymann\&.Navigation\&.NavigationConfig\&.GetLinkContainer ()\fR [abstract]\fP"

.PP
Return \fBILink\fP container\&. 
.PP
\fBReturns\fP
.RS 4
\fBILink\fP container
.RE
.PP

.SS "List< \fBINode\fP > Kunnymann\&.Navigation\&.NavigationConfig\&.GetNodeContainer ()\fR [abstract]\fP"

.PP
Return \fBINode\fP container\&. 
.PP
\fBReturns\fP
.RS 4
\fBINode\fP container
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
