.TH "Kunnymann.UI.ViewUnit" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.UI.ViewUnit \- UI를 구성하는 View의 최소 단위  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.RI "루트 캔버스에 View들을 집합 및 초기화합니다 "
.ti -1c
.RI "virtual void \fBStart\fP ()"
.br
.RI "등록된 OnChangedVisibleState 이벤트에 대한 리스너를 추가합니다 "
.ti -1c
.RI "virtual async UniTask \fBShow\fP ()"
.br
.RI "Show 애니메이션을 수행합니다 "
.ti -1c
.RI "virtual async UniTask \fBHide\fP ()"
.br
.RI "Hide 애니메이션을 수행합니다 "
.ti -1c
.RI "virtual void \fBShowImmediately\fP ()"
.br
.RI "즉시 Show를 수행합니다 "
.ti -1c
.RI "virtual void \fBHideImmediately\fP ()"
.br
.RI "즉시 Hide를 수행합니다 "
.ti -1c
.RI "virtual void \fBOnShow\fP ()"
.br
.RI "Show에 호출될 리스너 포맷 함수 "
.ti -1c
.RI "virtual void \fBOnShowing\fP ()"
.br
.RI "Showing에 호출될 리스너 포멧 함수 "
.ti -1c
.RI "virtual void \fBOnHide\fP ()"
.br
.RI "Hide에 호출될 리스너 포맷 함수 "
.ti -1c
.RI "virtual void \fBOnHiding\fP ()"
.br
.RI "Hiding에 호출될 리스너 포멧 함수 "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBUITransitionBase\fP > \fBUITransitions\fP\fR [get]\fP"
.br
.RI "TransitionBase 컨테이너를 반환하며, 없다면 초기화를 진행합니다 "
.ti -1c
.RI "CanvasGroup \fBCanvasGroup\fP\fR [get]\fP"
.br
.RI "TransitionBase 중, 가장 첫 번째 TransitionBase의 CanvasGroup을 반환 "
.ti -1c
.RI "\fBVisibleState\fP \fBVisibleState\fP\fR [get]\fP"
.br
.RI "TransitionBase 중, 가장 첫 번째 VisibleState를 반환 "
.ti -1c
.RI "UnityEvent< \fBVisibleState\fP > \fBChangedVisibleState\fP\fR [get]\fP"
.br
.RI "VisibleState 전이 이벤트 "
.in -1c
.SH "Detailed Description"
.PP 
UI를 구성하는 View의 최소 단위 
.SH "Member Function Documentation"
.PP 
.SS "virtual async UniTask Kunnymann\&.UI\&.ViewUnit\&.Hide ()\fR [protected]\fP, \fR [virtual]\fP"

.PP
Hide 애니메이션을 수행합니다 
.PP
\fBReturns\fP
.RS 4
UniTask
.RE
.PP

.SS "virtual async UniTask Kunnymann\&.UI\&.ViewUnit\&.Show ()\fR [protected]\fP, \fR [virtual]\fP"

.PP
Show 애니메이션을 수행합니다 
.PP
\fBReturns\fP
.RS 4
UniTask
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
