.TH "Kunnymann.Navigation.INavigationEventHandler" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Navigation.INavigationEventHandler \- \fBNavigation\fP event handler interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnReadyNavigationSession\fP ()"
.br
.RI "Called when the navigation session is ready\&. "
.ti -1c
.RI "void \fBOnStartNavigationSession\fP (\fBPath\fP path)"
.br
.RI "Called when the navigation session is started\&. "
.ti -1c
.RI "void \fBOnEndNavigationSession\fP (\fBSessionEndType\fP end)"
.br
.RI "Called when the navigation session is ended\&. "
.ti -1c
.RI "void \fBOnSessionStateChanged\fP (\fBNavigationState\fP state)"
.br
.RI "Called when the navigation session state is changed\&. "
.ti -1c
.RI "void \fBOnUpdatePath\fP (\fBPath\fP path)"
.br
.RI "Called when the navigation path is updated\&. "
.ti -1c
.RI "void \fBOnRecoveryPath\fP (\fBPath\fP path)"
.br
.RI "Called when the navigation path is recovered\&. "
.ti -1c
.RI "void \fBOnEnterTransition\fP (\fBINode\fP node)"
.br
.RI "Called when the target is entered transition zone\&. "
.ti -1c
.RI "void \fBOnExitTransition\fP (\fBINode\fP node)"
.br
.RI "Called when the target is exited transition zone\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBNavigation\fP event handler interface\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Kunnymann\&.Navigation\&.INavigationEventHandler\&.OnEndNavigationSession (\fBSessionEndType\fP end)"

.PP
Called when the navigation session is ended\&. 
.PP
\fBParameters\fP
.RS 4
\fIend\fP Session end type
.RE
.PP

.PP
Implemented in \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.
.SS "void Kunnymann\&.Navigation\&.INavigationEventHandler\&.OnEnterTransition (\fBINode\fP node)"

.PP
Called when the target is entered transition zone\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP transition zone node
.RE
.PP

.PP
Implemented in \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.
.SS "void Kunnymann\&.Navigation\&.INavigationEventHandler\&.OnExitTransition (\fBINode\fP node)"

.PP
Called when the target is exited transition zone\&. 
.PP
\fBParameters\fP
.RS 4
\fInode\fP 
.RE
.PP

.PP
Implemented in \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.
.SS "void Kunnymann\&.Navigation\&.INavigationEventHandler\&.OnReadyNavigationSession ()"

.PP
Called when the navigation session is ready\&. 
.PP
Implemented in \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.
.SS "void Kunnymann\&.Navigation\&.INavigationEventHandler\&.OnRecoveryPath (\fBPath\fP path)"

.PP
Called when the navigation path is recovered\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP

.PP
Implemented in \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.
.SS "void Kunnymann\&.Navigation\&.INavigationEventHandler\&.OnSessionStateChanged (\fBNavigationState\fP state)"

.PP
Called when the navigation session state is changed\&. 
.PP
\fBParameters\fP
.RS 4
\fIstate\fP \fBNavigation\fP session state
.RE
.PP

.PP
Implemented in \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.
.SS "void Kunnymann\&.Navigation\&.INavigationEventHandler\&.OnStartNavigationSession (\fBPath\fP path)"

.PP
Called when the navigation session is started\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP Current path
.RE
.PP

.PP
Implemented in \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.
.SS "void Kunnymann\&.Navigation\&.INavigationEventHandler\&.OnUpdatePath (\fBPath\fP path)"

.PP
Called when the navigation path is updated\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP

.PP
Implemented in \fBKunnymann\&.Navigation\&.NavigationBehaviour\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
