.TH "Kunnymann.Navigation" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Navigation
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAStarNode\fP"
.br
.RI "A* Node\&. "
.ti -1c
.RI "class \fBAStarPathGenerator\fP"
.br
.RI "A* \fBPath\fP Generator\&. "
.ti -1c
.RI "class \fBCurrentPoint\fP"
.br
.ti -1c
.RI "interface \fBILink\fP"
.br
.RI "Link interface\&. "
.ti -1c
.RI "interface \fBINavigationEventHandler\fP"
.br
.RI "\fBNavigation\fP event handler interface\&. "
.ti -1c
.RI "interface \fBINode\fP"
.br
.RI "Node interface\&. "
.ti -1c
.RI "class \fBNavigationBehaviour\fP"
.br
.RI "\fBNavigation\fP behaviour base class\&. "
.ti -1c
.RI "class \fBNavigationConfig\fP"
.br
.RI "\fBNavigation\fP configuration\&. "
.ti -1c
.RI "class \fBNavigationConst\fP"
.br
.ti -1c
.RI "class \fBNavigationModule\fP"
.br
.RI "\fBNavigation\fP module\&. "
.ti -1c
.RI "class \fBPath\fP"
.br
.RI "Node와 Link로 구성된 \fBPath\fP\&. "
.ti -1c
.RI "interface \fBPathUnit\fP"
.br
.RI "Units that make up the navigation path\&. "
.ti -1c
.RI "class \fBVector3Utility\fP"
.br
.RI "Vector3 utility\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNavigationState\fP { \fBNone\fP = 0, \fBReady\fP, \fBNavigation\fP, \fBWait\fP, \fBWrong\fP, \fBRecovery\fP, \fBEnd\fP }"
.br
.RI "Navigation module state\&. "
.ti -1c
.RI "enum \fBSessionEndType\fP { \fBArrived\fP = 0, \fBError\fP, \fBCanceled\fP }"
.br
.ti -1c
.RI "enum \fBLinkDirection\fP { \fBForward\fP, \fBBackward\fP, \fBBidirection\fP }"
.br
.RI "Link direction data\&. "
.ti -1c
.RI "enum \fBTransitionType\fP { \fBPath\fP, \fBEscalator\fP, \fBElevator\fP, \fBStairs\fP, \fBMovingWalkway\fP }"
.br
.RI "이동 수단 "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBKunnymann\&.Navigation\&.LinkDirection\fP"

.PP
Link direction data\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIForward \fP
Forward, One way\&. 
.TP
\f(BIBackward \fP
Backward, One way\&. 
.TP
\f(BIBidirection \fP
Bidirection, Two way\&. 
.SS "enum \fBKunnymann\&.Navigation\&.NavigationState\fP"

.PP
\fBNavigation\fP module state\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
Waiting for initialization\&. 
.TP
\f(BIReady \fP
Ready\&. 
.TP
\f(BINavigation \fP
Navigating\&. 
.TP
\f(BIWait \fP
Waiting for resume\&. 
.TP
\f(BIWrong \fP
Wrong path detected\&. 
.TP
\f(BIRecovery \fP
Recovery navigation\&. 
.TP
\f(BIEnd \fP
\fBNavigation\fP end\&. 
.SS "enum \fBKunnymann\&.Navigation\&.SessionEndType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIArrived \fP
Arrived at the destination\&. 
.TP
\f(BIError \fP
Error\&. 
.TP
\f(BICanceled \fP
Canceled\&. 
.SS "enum \fBKunnymann\&.Navigation\&.TransitionType\fP"

.PP
이동 수단 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIPath \fP
\fBPath\fP\&. 
.TP
\f(BIEscalator \fP
Escalator\&. 
.TP
\f(BIElevator \fP
Elevator\&. 
.TP
\f(BIStairs \fP
Stairs\&. 
.TP
\f(BIMovingWalkway \fP
Moving walkway\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
