.TH "Kunnymann.UI.Popup" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.UI.Popup
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPopupContainer\fP"
.br
.RI "UIPopup Prefab들을 관리하는 Container\&. "
.ti -1c
.RI "class \fBPopupUnit\fP"
.br
.RI "\fBPopup\fP GUI의 최소 단위인 MonoBeheviour\&. "
.ti -1c
.RI "class \fBPopupUtility\fP"
.br
.RI "\fBPopup\fP 확장 메소드 클래스 "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
