.TH "Kunnymann.Base.BaseObject" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.BaseObject \- 모듈 기본 오브젝트  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKunnymann\&.Base\&.CommonBase\fP\&.
.SH "Detailed Description"
.PP 
모듈 기본 오브젝트 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
