.TH "Kunnymann.Navigation.Vector3Utility" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Navigation.Vector3Utility \- Vector3 utility\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Vector3 \fBYZProject\fP (Vector3 vector)"
.br
.RI "Vector3 YZ projection\&. "
.ti -1c
.RI "static Vector3 \fBXZProject\fP (Vector3 vector)"
.br
.RI "Vector3 XZ projection\&. "
.ti -1c
.RI "static Vector3 \fBXYProject\fP (Vector3 vector)"
.br
.RI "Vector3 XY projection\&. "
.ti -1c
.RI "static float \fBGetYZDistance\fP (Vector3 vector1, Vector3 vector2)"
.br
.RI "Return distance between two vectors\&. "
.ti -1c
.RI "static float \fBGetXZDistance\fP (Vector3 vector1, Vector3 vector2)"
.br
.RI "Return distance between two XZ projected vectors\&. "
.ti -1c
.RI "static float \fBGetXYDistance\fP (Vector3 vector1, Vector3 vector2)"
.br
.RI "Return distance between two XY projected vectors\&. "
.in -1c
.SH "Detailed Description"
.PP 
Vector3 utility\&. 
.SH "Member Function Documentation"
.PP 
.SS "static float Kunnymann\&.Navigation\&.Vector3Utility\&.GetXYDistance (Vector3 vector1, Vector3 vector2)\fR [static]\fP"

.PP
Return distance between two XY projected vectors\&. 
.PP
\fBParameters\fP
.RS 4
\fIvector1\fP Vector 1
.br
\fIvector2\fP Vector 2
.RE
.PP
\fBReturns\fP
.RS 4
Distance
.RE
.PP

.SS "static float Kunnymann\&.Navigation\&.Vector3Utility\&.GetXZDistance (Vector3 vector1, Vector3 vector2)\fR [static]\fP"

.PP
Return distance between two XZ projected vectors\&. 
.PP
\fBParameters\fP
.RS 4
\fIvector1\fP Vector 1
.br
\fIvector2\fP Vector 2
.RE
.PP
\fBReturns\fP
.RS 4
Distance
.RE
.PP

.SS "static float Kunnymann\&.Navigation\&.Vector3Utility\&.GetYZDistance (Vector3 vector1, Vector3 vector2)\fR [static]\fP"

.PP
Return distance between two vectors\&. 
.PP
\fBParameters\fP
.RS 4
\fIvector1\fP Vector 1
.br
\fIvector2\fP Vector 2
.RE
.PP
\fBReturns\fP
.RS 4
Distance
.RE
.PP

.SS "static Vector3 Kunnymann\&.Navigation\&.Vector3Utility\&.XYProject (Vector3 vector)\fR [static]\fP"

.PP
Vector3 XY projection\&. 
.PP
\fBParameters\fP
.RS 4
\fIvector\fP Vector3
.RE
.PP
\fBReturns\fP
.RS 4
XY Vector3
.RE
.PP

.SS "static Vector3 Kunnymann\&.Navigation\&.Vector3Utility\&.XZProject (Vector3 vector)\fR [static]\fP"

.PP
Vector3 XZ projection\&. 
.PP
\fBParameters\fP
.RS 4
\fIvector\fP Vector3
.RE
.PP
\fBReturns\fP
.RS 4
XZ Vector3
.RE
.PP

.SS "static Vector3 Kunnymann\&.Navigation\&.Vector3Utility\&.YZProject (Vector3 vector)\fR [static]\fP"

.PP
Vector3 YZ projection\&. 
.PP
\fBParameters\fP
.RS 4
\fIvector\fP Vector3
.RE
.PP
\fBReturns\fP
.RS 4
YZ Vector3
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
