.TH "Kunnymann.Base.CommonBase" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.CommonBase \- 모듈 공통 인터페이스  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBKunnymann\&.Base\&.BaseBehaviour\fP, \fBKunnymann\&.Base\&.BaseObject\fP, and \fBKunnymann\&.Base\&.BaseScriptableObject\fP\&.
.SH "Detailed Description"
.PP 
모듈 공통 인터페이스 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
