.TH "Kunnymann.UI.DraggableHandle" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.UI.DraggableHandle \- 드래그 가능한 핸들 클래스  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IDragHandler, IEndDragHandler, and IBeginDragHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnBeginDrag\fP (PointerEventData eventData)"
.br
.RI "드래그 시작 이벤트 "
.ti -1c
.RI "void \fBOnDrag\fP (PointerEventData eventData)"
.br
.RI "드래그 이벤트 "
.ti -1c
.RI "void \fBOnEndDrag\fP (PointerEventData eventData)"
.br
.RI "드래그 종료 이벤트 "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDraggableHandleState\fP \fBState\fP\fR [get]\fP"
.br
.RI "현재 핸들의 상태 "
.in -1c
.SH "Detailed Description"
.PP 
드래그 가능한 핸들 클래스 
.SH "Member Function Documentation"
.PP 
.SS "void Kunnymann\&.UI\&.DraggableHandle\&.OnBeginDrag (PointerEventData eventData)"

.PP
드래그 시작 이벤트 
.PP
\fBParameters\fP
.RS 4
\fIeventData\fP 이벤트 데이터
.RE
.PP

.SS "void Kunnymann\&.UI\&.DraggableHandle\&.OnDrag (PointerEventData eventData)"

.PP
드래그 이벤트 
.PP
\fBParameters\fP
.RS 4
\fIeventData\fP 이벤트 데이터
.RE
.PP

.SS "void Kunnymann\&.UI\&.DraggableHandle\&.OnEndDrag (PointerEventData eventData)"

.PP
드래그 종료 이벤트 
.PP
\fBParameters\fP
.RS 4
\fIeventData\fP 이벤트 데이터
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
