.TH "Kunnymann.Base.BaseScriptableObject" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.BaseScriptableObject \- 모듈 기본 ScriptableObject  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject, and \fBKunnymann\&.Base\&.CommonBase\fP\&.
.PP
Inherited by \fBKunnymann\&.Base\&.ModuleBase\fP\&.
.SH "Detailed Description"
.PP 
모듈 기본 ScriptableObject 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
