.TH "Kunnymann.Base.ConstValue" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.ConstValue \- 상수값  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBMODULE_MANAGER_NAME\fP = 'ModuleManager'"
.br
.RI "\fBModuleManager\fP 게임 오브젝트 이름 "
.in -1c
.SH "Detailed Description"
.PP 
상수값 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
