.TH "Kunnymann.Base.Debugger.LogConst" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.Debugger.LogConst \- 디버거 로그 상수  

.SH SYNOPSIS
.br
.PP
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "const string \fBLOG_LEVEL_WORD_INFO\fP = '<color=white>[{0}]</color>'"
.br
.RI "Info 로그 레벨 Prefix\&. "
.ti -1c
.RI "const string \fBLOG_LEVEL_WORD_WARNING\fP = '<color=yellow>[{0}]</color>'"
.br
.RI "Warning 로그 레벨 Prefix\&. "
.ti -1c
.RI "const string \fBLOG_LEVEL_WORD_ERROR\fP = '<color=red>[{0}]</color>'"
.br
.RI "Error 로그 레벨 Prefix\&. "
.ti -1c
.RI "const string \fBLOG_LEVEL_WORD_FATAL\fP = '<color=red><b>[{0}]</b></color>'"
.br
.RI "Fatal 로그 레벨 Prefix\&. "
.ti -1c
.RI "const string \fBLOG_FORMAT\fP = '{0} {1}'"
.br
.RI "로그 포맷 "
.in -1c
.SH "Detailed Description"
.PP 
디버거 로그 상수 

.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
