.TH "Kunnymann.Base.POIModuleBase" 3 "Version 1.0" "Kunnymann unity package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kunnymann.Base.POIModuleBase \- POI DI 객체  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKunnymann\&.Base\&.ModuleBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAddPOI\fP (\fBPOIFeatureData\fP poi)"
.br
.RI "POI를 추가합니다 "
.in -1c

Public Member Functions inherited from \fBKunnymann\&.Base\&.ModuleBase\fP
.in +1c
.ti -1c
.RI "\fBModuleBase\fP ()"
.br
.RI "생성자 Default FMS를 구축합니다 "
.ti -1c
.RI "void \fBRunOnMainThread\fP (params Action[] action)"
.br
.RI "Main thread에 액션을 밀어넣습니다 "
.ti -1c
.RI "virtual void \fBModuleInitialize\fP ()"
.br
.RI "모듈의 초기화 사이클 "
.ti -1c
.RI "virtual void \fBModuleUpdate\fP ()"
.br
.RI "모듈의 Unity update 사이클 "
.ti -1c
.RI "virtual void \fBModuleTerminate\fP ()"
.br
.RI "모듈의 종료 사이클 "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Dispose\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual bool \fBInitialized\fP\fR [get]\fP"
.br
.RI "초기화 여부 "
.in -1c

Properties inherited from \fBKunnymann\&.Base\&.ModuleBase\fP
.in +1c
.ti -1c
.RI "\fBModuleState\fP \fBCurrentState\fP\fR [get]\fP"
.br
.RI "모듈 상태 "
.in -1c
.SS "Additional Inherited Members"


Package Functions inherited from \fBKunnymann\&.Base\&.ModuleBase\fP
.in +1c
.ti -1c
.RI "void \fBProcess\fP (\fBTransitionCommand\fP transition=\fBTransitionCommand\&.None\fP)"
.br
.RI "모듈 동작을 처리합니다 "
.in -1c
.SH "Detailed Description"
.PP 
POI DI 객체 
.SH "Member Function Documentation"
.PP 
.SS "virtual void Kunnymann\&.Base\&.POIModuleBase\&.AddPOI (\fBPOIFeatureData\fP poi)\fR [virtual]\fP"

.PP
POI를 추가합니다 
.PP
\fBParameters\fP
.RS 4
\fIpoi\fP POI 객체
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Kunnymann unity package from the source code\&.
