name: Verdaccio Unpublishing

# 패키지 명을 입력 받는다
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package name to publish'
        required: true
      version:
        description: 'Version for unpublish'
        required: true

jobs:
  validate-and-unpublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: ${{ vars.PACKAGE_URL }}

      # 패키지 언퍼블리싱 수행
      - name: Unpublish to Verdaccio
        run: |
          npm unpublish ${{ github.event.inputs.package }}@${{ github.event.inputs.version }} --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}
